#!/bin/bash
# ======================================================================
#          ------- Custom Functions -------                            #
#  Space for adding custom functions so each repo can customize as.    # 
#  needed.                                                             #
# ======================================================================


customFunction(){
  printInfoSection "This is a custom function that calculates 1 + 1"

  printInfo "1 + 1 = $(( 1 + 1 ))"

}

deployCronJobs() {
  printInfoSection "Deploying CronJobs for Astroshop for this lab"
  kubectl apply -f $REPO_PATH/.devcontainer/manifests/cronjobs.yaml
}

# ======================================================================
#   Step-by-step end-to-end verification + solution helpers
# ----------------------------------------------------------------------
#   Called from the lab pages' shell-verification and LAB_SOLUTION blocks.
#   Every Kubernetes/Dynatrace action is asynchronous, so each helper
#   WAITS (bounded retry) for the expected state instead of checking once.
#   This lets the Enablement App (and the app-layer-test driver) verify a
#   step right after the previous one without racing the rollout. Mirrors
#   the Kubernetes 101 golden pattern.
# ======================================================================

# Cluster node reaches Ready.
waitForNodeReady() {
  printInfoSection "Waiting for the cluster node to be Ready"
  local i=0
  while [ "$i" -lt 24 ]; do
    [ "$(kubectl get nodes --no-headers 2>/dev/null | grep -c ' Ready')" -gt 0 ] && { printInfo "node Ready"; return 0; }
    i=$((i + 1)); printInfo "node not Ready yet ($i/24), waiting 5s"; sleep 5
  done
  printError "Cluster node not Ready in time"; return 1
}

# AstroShop demo app has at least one Running pod. AstroShop is heavy and is
# deployed at postCreate, so give it a generous window before failing.
waitForAstroshop() {
  printInfoSection "Waiting for the AstroShop demo app pods to be Running"
  local i=0
  while [ "$i" -lt 48 ]; do
    [ "$(kubectl get pods -n astroshop --no-headers 2>/dev/null | grep -c Running)" -gt 0 ] && { printInfo "AstroShop Running"; return 0; }
    i=$((i + 1)); printInfo "AstroShop not Running yet ($i/48), waiting 10s"; sleep 10
  done
  printError "AstroShop pods not Running in time"; return 1
}

# Dynatrace Operator manager pod reaches Running (Section 4, step 1).
waitForOperatorReady() {
  printInfoSection "Waiting for the Dynatrace Operator pod to be Running"
  local i=0
  while [ "$i" -lt 36 ]; do
    kubectl get pods -n dynatrace --no-headers 2>/dev/null | grep -E 'operator' | grep -q Running && { printInfo "operator Running"; return 0; }
    i=$((i + 1)); printInfo "operator not Running yet ($i/36), waiting 5s"; sleep 5
  done
  printError "Dynatrace Operator pod not Running in time"; return 1
}

# At least two DynaKube custom resources exist (the k8s+log DynaKube and the
# agents DynaKube) - Section 4, step 2.
waitForTwoDynakubes() {
  printInfoSection "Waiting for the two DynaKube custom resources"
  local i=0
  while [ "$i" -lt 30 ]; do
    [ "$(kubectl get dynakube -n dynatrace --no-headers 2>/dev/null | grep -c '')" -gt 1 ] && { printInfo "two DynaKubes present"; return 0; }
    i=$((i + 1)); printInfo "fewer than two DynaKubes yet ($i/30), waiting 5s"; sleep 5
  done
  printError "Two DynaKube custom resources not found in time"; return 1
}

# Log Module (logmonitoring) pod reaches Running (Section 4, step 2).
waitForLogModule() {
  printInfoSection "Waiting for the Dynatrace Log Module (logmonitoring) pod to be Running"
  local i=0
  while [ "$i" -lt 36 ]; do
    kubectl get pods -n dynatrace --no-headers 2>/dev/null | grep logmonitoring | grep -q Running && { printInfo "Log Module Running"; return 0; }
    i=$((i + 1)); printInfo "Log Module not Running yet ($i/36), waiting 10s"; sleep 10
  done
  printError "Log Module pod not Running in time"; return 1
}

# --- Solution helper: deploy the two DynaKubes the lab teaches ---------
# DynaKube #1 (k8s-only mode) is generated by the framework and includes the
# Log Module (DK_LOG_MONITORING defaults true) scoped to the astroshop
# namespace. DynaKube #2 (agents) adds Application Observability. Together they
# satisfy the "two DynaKubes" and "Log Module Running" checks - the same
# architecture documented in section 4. Assumes the Operator is already
# deployed (dynatraceDeployOperator) and the token secret ($RepositoryName)
# exists.
deployLogIngestDynakubes() {
  printInfoSection "Deploying the Kubernetes+Log Module DynaKube and the Agents DynaKube"

  # DynaKube #1: Kubernetes platform monitoring + Log Module (no OneAgent).
  # k8s-only mode leaves out the oneAgent section; log monitoring is on by default.
  DK_LOG_MONITORING=true deployDynatrace k8s-only

  # Patch DynaKube #1:
  #  - scope the Log Module ingest rule to the astroshop namespace (as the lab teaches);
  #  - DISABLE metadataEnrichment. The framework enables it on #1 with no
  #    namespaceSelector, which makes #1 claim ALL namespaces via the mutating
  #    webhook. The operator then rejects the agents DynaKube #2 with
  #    "tries to inject into namespaces where another Dynakube already injects
  #    into". Turning enrichment off on the k8s/log DynaKube lets the agents
  #    DynaKube own application injection for astroshop.
  # The framework derives the DynaKube name per user (per-user Grail isolation
  # renames it from $RepositoryName), so resolve the ACTUAL DynaKube #1 name —
  # patching the old fixed name silently failed and the webhook then rejected
  # DynaKube #2 with "another Dynakube already injects into these namespaces".
  local dk1
  dk1=$(kubectl get dynakube -n dynatrace -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
  kubectl -n dynatrace patch dynakube "${dk1:-$RepositoryName}" --type merge \
    -p '{"spec":{"metadataEnrichment":{"enabled":false},"logMonitoring":{"ingestRuleMatchers":[{"attribute":"k8s.namespace.name","values":["astroshop"]}]}}}' \
    || printWarn "Could not patch DynaKube ${dk1:-$RepositoryName} — the agents DynaKube may be rejected"

  # DynaKube #2: Application Observability agents DynaKube. References the same
  # token secret created by dynatraceDeployOperator ($RepositoryName).
  # Constraints learned from the operator's validating webhook:
  #  - DynaKube name must be <= 40 chars (it is the base for resource names), so
  #    use the short name "logingest-agents" (not ${RepositoryName}-agents = 42).
  #  - applicationMonitoring must set a namespaceSelector; the injection selector
  #    lives at spec.oneAgent.applicationMonitoring.namespaceSelector in v1beta6.
  #    Scope it to the astroshop namespace so it does not conflict with #1.
  printInfo "Applying the agents DynaKube (Application Observability, scoped to astroshop)"
  local agents_out
  agents_out=$(kubectl apply -f - 2>&1 <<AGENTS_DK
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: logingest-agents
  namespace: dynatrace
spec:
  apiUrl: ${DT_TENANT}/api
  tokens: ${RepositoryName}
  oneAgent:
    applicationMonitoring:
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: astroshop
  activeGate:
    capabilities:
      - routing
      - debugging
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 768Mi
    replicas: 1
AGENTS_DK
)
  printInfo "agents DynaKube apply: ${agents_out}"

  printInfo "Both DynaKubes applied. The Operator will reconcile the Log Module and agents."
}