site_name: "Dynatrace Enablement Lab: Log Ingest 101"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/enablement-dynatrace-log-ingest-101"
nav:
  - '1. About': index.md
  - '2. Getting started': 2-getting-started.md
  - '3. Codespaces': 3-codespaces.md
  - '4. Deploy Dynatrace': 4-deploy-dynatrace.md
  - '5. Configure Dynatrace': 5-configure-dynatrace.md
  - '6. Analyze Logs': 6-analyze-logs.md
  - '7. Cleanup': cleanup.md
theme:
  name: material
  custom_dir: docs/overrides
  logo: https://cdn.bfldr.com/B686QPH3/at/w5hnjzb32k5wcrcxnwcx4ckg/Dynatrace_signet_RGB_HTML.svg?auto=webp&format=pngg
  features:
    - content.code.copy
    
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    primary: deep-purple
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    primary: deep-purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep-purple
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: '#'
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ["docs"]
  - attr_list
plugins:
    - search
